### ISSUE TITLE
Does edgegrid-curl connect via TLS 1.2 or higher?

### ISSUE THREAD

**Issue by nshenry03** [akamai/edgegrid-curl#26]
Hey there, we just got an email from Akamai about needing to use TLS 1.2 by January 7th.  If I understand correctly, egcurl is a wrapper for curl right?  If so, we should be able to test to be sure that egcurl will work on January 7th with something like this?

```bash
curl -s https://www.ssllabs.com/ssltest/viewMyClient.html | w3m -T text/html -dump | grep -A8 Protocols
```

```
Protocols
TLS 1.3                                            No
TLS 1.2                                            Yes*
TLS 1.1                                            Yes*
TLS 1.0                                            Yes*
SSL 3                                              Yes*
SSL 2                                              No
(*) Without JavaScript, this test reliably detects only the highest supported
protocol.
```

As long as TLS 1.2 is a `Yes`, we should be good I assume?

**Comment by elreydetodo** [comment]
Correct. If your `curl` binary supports TLS 1.2 then you should have no problem with edgegrid-curl supporting it as well.
