### ISSUE TITLE
What is the workaround for a method PATCH

### ISSUE THREAD

**Issue by mikelupo** [akamai/edgegrid-curl#29]
The code only allows GET, POST, DELETE and PUT, but why not PATCH? Some Akamai open API calls require patch.
such as: adding/removing hostnames in the PAPI v1 API

For curl, Stackoverflow mentions passing the PATCH in as a --request parameter instead of -X
https://stackoverflow.com/questions/16306624/how-to-use-patch-verb-with-curl

thoughts?

**Comment by elreydetodo** [comment]
The only reason for the lack of support is that PATCH wasn't widely used at the time this tool was created. I'm happy to review a PR if you'd like to submit one. Otherwise I'll try to address it sometime in the next couple weeks.

**Comment by elreydetodo** [comment]
Is the only problem that the -X argument doesn't support "PATCH"? I am not sure if there's anything else necessary to make this work but I don't think so. I don't know of any API calls I can use to test it though. I can push a patch to enable the method but can't guarantee it will fully resolve the issue.

**Comment by mikelupo** [comment]
thanks. I had tried to submit a PR, but for some reason I kept getting a 401.  I did edit it locally (same edit you made) and try it out before-hand and it worked so I presume that your submission will be fine.. Thank you again.
