### ISSUE TITLE
URL should not always be last argument

### ISSUE THREAD

**Issue by bacalec** [akamai/edgegrid-curl#31]
Problem: When an argument unknown to edgegrid-curl is provided with a value before url argument:
- the name of this argument is added to args_unknown without its value.
- Its value is assigned to argument url.
- url provided is added to args_unknown

```
$ egcurl --eg-verbose --eg-verbose -q --config "$HOME/.curlrc.noheader" https://luna.akamaiapis.net/identity-management/v2/api-clients/self/credentials 2>&1 |head -n 4
INFO:__main__:Parsed known arguments: Namespace(data=None, data_binary=None, eg_config='/home/aberdin/.egcurl', eg_edgerc='/home/aberdin/.edgerc', eg_json=False, eg_section='default', eg_verbose=2, header=[], method='GET', url='/home/aberdin/.curlrc.noheader')
DEBUG:__main__:Pass-through cURL arguments: ['-q',
 '--config',
 'https://luna.akamaiapis.net/identity-management/v2/api-clients/self/credentials']
```

Note: url argument does not need to be provided in last position.

```
$ egcurl --eg-verbose --eg-verbose -q https://luna.akamaiapis.net/identity-management/v2/api-clients/self/credentials --config "$HOME/.curlrc.noheader"  2>&1 |head -n 2
INFO:__main__:Parsed known arguments: Namespace(data=None, data_binary=None, eg_config='/home/aberdin/.egcurl', eg_edgerc='/home/aberdin/.edgerc', eg_json=False, eg_section='default', eg_verbose=2, header=[], method='GET', url='https://luna.akamaiapis.net/identity-management/v2/api-clients/self/credentials')
DEBUG:__main__:Pass-through cURL arguments: ['-q', '--config', '/home/aberdin/.curlrc.noheader']
```

Proposed solution: Update documentation to explain that argument url needs to be provided before any argument unknown to edgegrid-curl that is provided with a value.

**Comment by elreydetodo** [comment]
I agree we are doing something wrong here, but I don't think documentation is the right way to do. Ideally we should fix the python code to hunt through all the unnamed arguments to find one that looks like a URL. Matching the values on starting with "https://" would be enough. The current behavior seems to be fallout from how we've used the Python argument parser.

I'm not totally sure how to accomplish both the `--help` output working (which comes automatically with using ArgumentParser) and supporting that url can be hidden anywhere within the string. If you would like to submit a PR I'll take a look.

**Comment by bacalec** [comment]
We could pass a reordered argument array to the parser, instead of letting it take sys.argv by default.
In this array, we could could move the url to 1st position (or 2nd position if sys.argv start with -q)
 
Otherwise, we may use a custom action, but I don't know how it works.

I see 2 difficulties with matching the value on starting with "https://"

1. curl accepts options with values that can start with "https://", for example:
--data <data>
--data-ascii <data>
--data-binary <data>
--data-raw <data>
--data-urlencode <data>
--doh-url <URL>

2. url don't need to start with "https://' if option --proto-default https is used:
curl --proto-default https www.example.com

**Comment by elreydetodo** [comment]
PR #33 does a good job of addressing this, at least as good as we probably can do given the constraints or cURL and the signing algorithm. Thanks for the patch!
